### PR TITLE
Updated Font Awesome Support

### PR DESCRIPTION
**Pull request by stephaniewillhide**
This pull request aims to update our Font Awesome library. I've followed the instructions in the readme to make this update.

I've also tagged this v1.0.6. Let me know if I need to do anything else to get this working. Thanks!

### CODE REVIEW

**Comment by stephaniewillhide** [comment]
Hi @interexchange/engineers-website, I was hoping to update our Font Awesome library. I didn't have access to create a pull request or request your review, so I have forked it and am commenting here. Thanks!

**Comment by stephaniewillhide** [comment]
Hi @interexchange/engineers-website, just checking in on this one. Thanks!

**Comment by dirkkelly** [comment]
This repository was missing team permissions for `marketing` `engineers-website` so that they can be added to future reviews.

**Review by kevin-jackson — APPROVED** [review]

**Comment by stephaniewillhide** [comment]
Thanks!

**Pull request merged**
